### ISSUE TITLE
Fix Installation instructions for terminal icons 

### ISSUE THREAD

**Issue by yevhen-logosha** [dhanishgajjar/terminal-icons#10]
Hi mate. 
Great job on icons!!
Small suggestion..
Thing is it looks like you need to fix installation manual for Terminal icons.
Sure it is kind of the same but imho would look better!

Great work again! 💪

**Comment by dhanishgajjar** [comment]
@yevhen-logosha I've improved the macOS installation instructions. Will add Win and Linux soon.
